declare const ALLDEBRID_AGENT: string
declare const ALLDEBRID_KEY: string
declare const OMDB_KEY: string
declare const ORION_APP: string
declare const ORION_KEY: string
declare const PREMIUMIZE_ID: string
declare const PREMIUMIZE_PIN: string
declare const REALDEBRID_ID: string
declare const REALDEBRID_SECRET: string
declare const SIMKL_ID: string
declare const SIMKL_SECRET: string
declare const TMDB_KEY: string
declare const TRAKT_CLIENT_ID: string
declare const TRAKT_CLIENT_SECRET: string
declare const TVDB_KEY: string
declare const TVDB_TOKEN: string
declare const TVMAZE_KEY: string
